services:
  app:
    image: ${APP_DOCKER_IMAGE}
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - .env

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:${BACKEND_PORT}/api/v1
      - NEXT_SERVER_API_URL=http://app:${BACKEND_PORT}/api/v1
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

